/**
 * @fileoverview Repository for user-initiated content moderation reports.
 *
 * ARCHITECTURAL ROLE:
 * Implements the Repository Pattern for content flagging/reporting. This is part of
 * the moderation workflow where users can report inappropriate, offensive, or broken content.
 *
 * FIRESTORE SCHEMA:
 * - Collection: "content_reports"
 * - Document ID: Auto-generated by addDoc() (append-only event log)
 * - Fields: user_id, content_id, content_type, category, description, status, reported_at
 *
 * WORKFLOW:
 * - User encounters problematic content and clicks "Report"
 * - UI collects category (harassment, misinformation, etc.) and optional description
 * - Repository writes report document with DEFAULT_REPORT_STATUS = "open"
 * - Moderation dashboard (admin app) queries "open" reports for review
 * - Admin marks as resolved/dismissed, updating status field
 *
 * DESIGN PATTERNS:
 * - Repository Pattern: Encapsulates write-only operation
 * - Append-Only Log: Reports are immutable after creation
 * - Server Timestamp: Ensures audit trail integrity
 *
 * CONSUMERS:
 * - Report UI: Collects and submits user reports
 * - Admin moderation: Queries and reviews open reports
 *
 * NOTE:
 * - This module currently only handles report creation (write)
 * - Report querying/updating is handled in admin repository
 */

import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import { db } from "@/firebase";
import { ContentReportStatus, ReportCategory } from "@/types";

const contentReportsCollection = collection(db, "content_reports");
// Initial status for all new reports - workflow state
const DEFAULT_REPORT_STATUS: ContentReportStatus = "open";

/**
 * Creates a new content moderation report submitted by a user.
 *
 * FIRESTORE OPERATION:
 * - Write: addDoc() appends a new document to content_reports collection
 * - Auto-generates document ID (no composite key needed for reports)
 * - Writes immutable record with server timestamp and initial status
 *
 * WORKFLOW:
 * 1. User discovers problematic content and submits report
 * 2. Function writes report to Firestore with status = "open"
 * 3. Moderation admin queries open reports for review
 * 4. Admin actions (approve/dismiss) update the status field (outside this module)
 *
 * AUDIT TRAIL:
 * - All fields recorded to maintain complete history
 * - reported_at uses server timestamp for clock independence
 * - userId stored for potential abuse detection (repeated reporters)
 *
 * ERROR HANDLING:
 * - Returns false on error rather than throwing
 * - Allows UI to show "Report failed, try again" without crashing
 *
 * @param userId - User submitting the report (for audit/abuse detection)
 * @param contentId - ID of the problematic content
 * @param contentType - Type/category of content (e.g., 'meditation', 'course')
 * @param category - Reason for report (harassment, misinformation, etc.) - enum value
 * @param description - Optional user-provided details about the problem
 * @returns Promise<boolean> - true on success, false on error
 */
export async function reportContent(
  userId: string,
  contentId: string,
  contentType: string,
  category: ReportCategory,
  description?: string
): Promise<boolean> {
  try {
    // Append-only write: each report is a unique document
    await addDoc(contentReportsCollection, {
      user_id: userId,
      content_id: contentId,
      content_type: contentType,
      category,
      description: description || null, // Allow omission but store null to be explicit
      status: DEFAULT_REPORT_STATUS, // Initially "open" for moderation review
      reported_at: serverTimestamp(),
    });
    return true;
  } catch (error) {
    console.error("Error reporting content:", error);
    return false;
  }
}
