/**
 * @fileoverview Repository for managing user content ratings and preferences.
 *
 * ARCHITECTURAL ROLE:
 * Implements the Repository Pattern to abstract Firestore operations for user ratings.
 * Supports the "toggle" semantic where clicking a rating button adds or removes the rating.
 *
 * FIRESTORE SCHEMA:
 * - Collection: "content_ratings"
 * - Document ID: Auto-generated by addDoc() (allows multiple rating records per user+content)
 * - Fields: user_id, content_id, content_type, rating, rated_at (server timestamp)
 *
 * DESIGN PATTERNS:
 * - Repository Pattern: Encapsulates Firestore mutations and queries
 * - Toggle Semantics: setContentRating() adds rating or deletes if same rating clicked again
 * - Server Timestamp: Ensures clock-skew resistant audit trails
 *
 * KEY BEHAVIORS:
 * - If user rates content with rating A, then rates with A again -> rating deleted (toggle)
 * - If user rates with A, then rates with B -> record updated to B
 * - getUserRating() returns only the current rating (expects one record per user+content)
 *
 * CONSUMERS:
 * - UI: Rating buttons showing like/dislike/neutral states
 * - Analytics: Aggregate ratings for content recommendations
 * - Content moderation: Flag low-rated content
 */

import {
  addDoc,
  collection,
  deleteDoc,
  getDocs,
  query,
  serverTimestamp,
  setDoc,
  where,
} from "firebase/firestore";
import { db } from "@/firebase";
import { RatingType } from "@/types";

const contentRatingsCollection = collection(db, "content_ratings");

/**
 * Retrieves a user's current rating for a piece of content.
 *
 * FIRESTORE QUERY:
 * - Composite filter: user_id == userId AND content_id == contentId
 * - Expected to return 0 or 1 documents (one rating per user+content)
 * - Returns first doc if multiple exist (edge case handling)
 *
 * RETURN TYPE:
 * - RatingType | null: null if no rating exists, otherwise the rating value
 * - Consider caching results since this is called frequently in UI render
 *
 * DESIGN NOTE:
 * - Queries all rating documents for user+content (should be 1 or 0)
 * - Alternative: use composite key doc ID strategy for O(1) lookup
 *   (would require refactoring storage layer)
 *
 * @param userId - User identifier
 * @param contentId - Content identifier
 * @returns Promise<RatingType | null> - Current rating or null if unrated
 */
export async function getUserRating(
  userId: string,
  contentId: string
): Promise<RatingType | null> {
  try {
    // Composite query to find existing rating (should return 0 or 1 doc)
    // Expected: one rating per user+content pair
    const q = query(
      contentRatingsCollection,
      where("user_id", "==", userId),
      where("content_id", "==", contentId)
    );
    const snapshot = await getDocs(q);

    if (snapshot.empty) {
      return null;
    }

    // Return the first (and expected only) rating document
    // If multiple exist (data corruption), just return the first one
    return snapshot.docs[0].data().rating as RatingType;
  } catch (error) {
    console.error("Error getting user rating:", error);
    // Return null on error: assume no rating rather than throwing
    return null;
  }
}

/**
 * Sets or toggles a user's rating for content.
 *
 * BEHAVIOR (Toggle Semantics):
 * 1. If no rating exists -> creates new rating document
 * 2. If rating exists and is different -> updates to new rating
 * 3. If rating exists and is same -> deletes rating (toggle OFF)
 *
 * FIRESTORE OPERATIONS:
 * - Query: Find existing rating for user+content pair
 * - Delete: If user clicks same rating again (toggle off)
 * - Update: setDoc() if changing rating value
 * - Create: addDoc() if first rating for this content
 *
 * RETURN VALUE:
 * - Returns the new rating value on create/update
 * - Returns null on delete (rating was toggled off)
 * - Returns null on error (silent failure with logging)
 *
 * IDEMPOTENCY NOTE:
 * - Not idempotent: calling twice with same rating deletes on second call
 * - This is intentional toggle behavior for UI buttons
 *
 * @param userId - User identifier
 * @param contentId - Content identifier
 * @param contentType - Content category (for analytics)
 * @param rating - Rating value to set (must be RatingType enum value)
 * @returns Promise<RatingType | null> - New rating state, or null if toggled off
 */
export async function setContentRating(
  userId: string,
  contentId: string,
  contentType: string,
  rating: RatingType
): Promise<RatingType | null> {
  try {
    // Check if user has already rated this content
    const q = query(
      contentRatingsCollection,
      where("user_id", "==", userId),
      where("content_id", "==", contentId)
    );
    const snapshot = await getDocs(q);

    if (!snapshot.empty) {
      const existingDoc = snapshot.docs[0];
      const existingRating = existingDoc.data().rating as RatingType;

      // TOGGLE SEMANTICS: clicking same rating again removes it
      // UX: user sees rating button toggle on/off, not replace
      if (existingRating === rating) {
        await deleteDoc(existingDoc.ref);
        return null; // Signal to UI that rating is now deleted
      }

      // User changed rating from one value to another (e.g., like -> dislike)
      // Update existing document rather than creating new one
      await setDoc(existingDoc.ref, {
        user_id: userId,
        content_id: contentId,
        content_type: contentType,
        rating,
        rated_at: serverTimestamp(),
      });
      return rating;
    }

    // First rating for this user+content pair
    // Use addDoc() to allow auto-generated IDs (unlike completedContent composite keys)
    await addDoc(contentRatingsCollection, {
      user_id: userId,
      content_id: contentId,
      content_type: contentType,
      rating,
      rated_at: serverTimestamp(),
    });
    return rating;
  } catch (error) {
    console.error("Error setting content rating:", error);
    // Return null on error: rating operation failed, UI should reflect previous state
    return null;
  }
}
