/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/create`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/__tests__/layout.test`; params?: Router.UnknownInputParams; } | { pathname: `/admin/content`; params?: Router.UnknownInputParams; } | { pathname: `/admin/content/reports`; params?: Router.UnknownInputParams; } | { pathname: `/admin/content/[collection]/[id]`, params: Router.UnknownInputParams & { collection: string | number;id: string | number; } } | { pathname: `/admin/job/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/admin/job/[id]/review`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/admin/job/[id]/review/[sessionCode]`, params: Router.UnknownInputParams & { id: string | number;sessionCode: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/create`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/__tests__/layout.test`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/content`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/content/reports`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/content/[collection]/[id]`, params: Router.UnknownOutputParams & { collection: string;id: string; } } | { pathname: `/admin/job/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/admin/job/[id]/review`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/admin/job/[id]/review/[sessionCode]`, params: Router.UnknownOutputParams & { id: string;sessionCode: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/create${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/admin/__tests__/layout.test${`?${string}` | `#${string}` | ''}` | `/admin/content${`?${string}` | `#${string}` | ''}` | `/admin/content/reports${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/create`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/__tests__/layout.test`; params?: Router.UnknownInputParams; } | { pathname: `/admin/content`; params?: Router.UnknownInputParams; } | { pathname: `/admin/content/reports`; params?: Router.UnknownInputParams; } | `/admin/content/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/admin/job/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/admin/job/${Router.SingleRoutePart<T>}/review${`?${string}` | `#${string}` | ''}` | `/admin/job/${Router.SingleRoutePart<T>}/review/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/admin/content/[collection]/[id]`, params: Router.UnknownInputParams & { collection: string | number;id: string | number; } } | { pathname: `/admin/job/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/admin/job/[id]/review`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/admin/job/[id]/review/[sessionCode]`, params: Router.UnknownInputParams & { id: string | number;sessionCode: string | number; } };
    }
  }
}
